license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/antth-Luca/ModRedReign"
logoFile="logo.png"
authors="antthLuca"
description='''
Example mod description.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="curios"
type="required"
versionRange="[${curios_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="puffish_attributes"
type="required"
versionRange="[0.8.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"