org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Dependencies
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.101

curios_version=15.0.0+26.1.2
jei_version=29.35.0.94
pf_attrbts_file_id=7830516

## Mod Properties
mod_id=red_reign
mod_name=Red Reign
mod_license=All Rights Reserved
mod_version=1.0
mod_group_id=io.github.anttluca.red_reign